### ISSUE TITLE
Add the funtionality to update the screen when the buttons are clicked and result is calculated

### ISSUE THREAD

**Issue by rudyt7** [hackclubnmit/Simple-Calculator-Hacktoberfest2020#3]

**Comment by Baibhab97** [comment]
Please assign the same to me.

**Comment by rudyt7** [comment]
Yeah go ahead and work on it.

**Comment by aryasurya21** [comment]
can you assign this to me? i've got the solution @rudyt7

**Comment by rudyt7** [comment]
Yeah @aryasurya21 go ahead. We will be accepting the 1st PR which gets the functionality correct.

**Comment by aryasurya21** [comment]
i have opened a pull request @rudyt7 , please kindly check whether they are accepted or not, thanks.
