### ISSUE TITLE
Bug - multiple decimal points per number 

### ISSUE THREAD

**Issue by rpollock03** [hackclubnmit/Simple-Calculator-Hacktoberfest2020#9]
Current app allows multiple decimal points per number so user can input a number like "4.5.5.6....2" etc. This is obviously a problem. I'd like to fix this so that only one decimal point can feature per displayed number and number cannot start with a decimal point. Please assign.

**Comment by rudyt7** [comment]
go ahead :+1:

**Comment by rpollock03** [comment]
Thanks @rudyt7 , I have fixed this issue and submitted a pull request (my first ever pull request!). Thanks.

**Comment by pulkithanda** [comment]
please assign me this @rudyt7

**Comment by rpollock03** [comment]
@Pulkitchamp It was already assigned to me and I have submitted a pull request.

**Comment by pulkithanda** [comment]
it's still open though @rpollock03

**Comment by rpollock03** [comment]
Yea I was waiting for @rudyt7 to accept pull request

**Comment by rudyt7** [comment]
@Pulkitchamp  PR by @rpollock03  solves this issue
